window._EntrantRatingInitialItems = [
    {
        "botName": "Целевики",
        "basisOfTraining": 3,
        "sortIndex1": 1,
        "targetOrganization": "Горьковская железная дорога - филиал ОАО \"РЖД\"",
        "idOrganization": 465987,
        "targetPlan": 3,
        "showOrganization": false,
        "sortIndex2": 1,
        "receptionStatus": "Зачислены",
        "idLev3": 3,
        "sortIndex3": -201,
        "receptionType": "по конкурсу",
        "idLev4": 15,
        "sortIndex4": 15,
        "entrants": [
            {
                "entrantPhotoUrl": "http://miit.ru/content/e990842.jpg?id_fe=990842",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e990842.jpg?id_fe=990842&SWidth=75",
                "entrantFio": "Лукьянов Дмитрий Владимирович",
                "points": 176,
                "pointList": "69; 45; 62",
                "pointListDisplay": "Русский язык: 69;Математика: 45;Физика: 62",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "средняя школа",
                "idE": 990842,
                "recordStatus": 1,
                "entrantUrl": "/people/990842",
                "ratingIndex": 1
            },
            {
                "entrantPhotoUrl": "http://miit.ru/content/e989285.jpg?id_fe=989285",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e989285.jpg?id_fe=989285&SWidth=75",
                "entrantFio": "Чагин Артем Владиславович",
                "points": 165,
                "pointList": "67; 50; 48",
                "pointListDisplay": "Русский язык: 67;Математика: 50;Физика: 48",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "гимназия",
                "idE": 989285,
                "recordStatus": 1,
                "entrantUrl": "/people/989285",
                "ratingIndex": 2
            }]
    },

    {
        "botName": "Целевики",
        "basisOfTraining": 3,
        "sortIndex1": 1,
        "targetOrganization": "Государственное унитарное предприятие города Москвы \"Московский ордена Ленина и ордена Трудового Красного Знамени метрополитен имени В.И. Ленина\"",
        "idOrganization": 66719,
        "targetPlan": 5,
        "showOrganization": false,
        "sortIndex2": 2,
        "receptionStatus": "Зачислены",
        "idLev3": 3,
        "sortIndex3": -201,
        "receptionType": "по конкурсу",
        "idLev4": 15,
        "sortIndex4": 15,
        "entrants": [
            {
                "entrantPhotoUrl": "http://miit.ru/content/e992379.jpg?id_fe=992379",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e992379.jpg?id_fe=992379&SWidth=75",
                "entrantFio": "Карпухина Александра Александровна",
                "points": 175,
                "pointList": "78; 39; 48; 10",
                "pointListDisplay": "Русский язык: 78;Математика: 39;Физика: 48;Дополнительно: 10",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "средняя школа",
                "idE": 992379,
                "recordStatus": 1,
                "entrantUrl": "/people/992379",
                "ratingIndex": 1
            },
            {
                "entrantPhotoUrl": "http://miit.ru/content/e992697.jpg?id_fe=992697",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e992697.jpg?id_fe=992697&SWidth=75",
                "entrantFio": "Лаптев Михаил Александрович",
                "points": 174,
                "pointList": "73; 50; 51",
                "pointListDisplay": "Русский язык: 73;Математика: 50;Физика: 51",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "средняя школа",
                "idE": 992697,
                "recordStatus": 1,
                "entrantUrl": "/people/992697",
                "ratingIndex": 2
            },
            {
                "entrantPhotoUrl": "http://miit.ru/content/e992412.jpg?id_fe=992412",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e992412.jpg?id_fe=992412&SWidth=75",
                "entrantFio": "Савинков Никита Андреевич",
                "points": 150,
                "pointList": "66; 39; 45",
                "pointListDisplay": "Русский язык: 66;Математика: 39;Физика: 45",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "средняя школа",
                "idE": 992412,
                "recordStatus": 1,
                "entrantUrl": "/people/992412",
                "ratingIndex": 3
            },
            {
                "entrantPhotoUrl": "http://miit.ru/content/e992569.jpg?id_fe=992569",
                "entrantPhotoPreviewUrl": "http://miit.ru/content/e992569.jpg?id_fe=992569&SWidth=75",
                "entrantFio": "Беличев Сергей Сергеевич",
                "points": 128,
                "pointList": "51; 33; 44",
                "pointListDisplay": "Русский язык: 51;Математика: 33;Физика: 44",
                "originalDocumentStatus": "оригинал, согласие",
                "originalDocumentStatusShort": "оригинал",
                "schoolType": "колледж",
                "idE": 992569,
                "recordStatus": 1,
                "entrantUrl": "/people/992569",
                "ratingIndex": 4
            }
        ]
    }
]